---
title: "Golden Age vs Neo Liberalism Period"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

```{r, data, echo = FALSE}
library(knitr)
Fifth <- factor(5:1, levels = 5:1, labels = paste(c("Top", "Fourth", "Third", "Second", "Bottom"), "Fifth"))
Golden_Age <- c(99, 115, 113, 101, 122)
Neo_Liberal <- c(55, 25, 15, 7, -4)
Income_Gains_df <- data.frame(Fifth, Golden_Age, Neo_Liberal)
# str(Income_Gains_df)
kable(Income_Gains_df)
```

## Bar Plots

```{r, barplots, echo = FALSE, fig.width = 12, fig.height = 6}
par(mfrow = c(1, 2), mai = c(1.0, 1.8, 0.8, 0.4) + 0.2)
# par(mfrow = c(1, 2))
x1 <- barplot(Golden_Age, horiz = TRUE, col = "tan", 
              axes = FALSE, names.arg = "", 
              xlim = c(0, 140), space = 0.5, las = 1, 
              axisnames = TRUE)
title_1 <- "Golden Age\n1947 ~ 1979"
# title(main = title_1)
title(main = title_1, cex.main = 2.0)
abline(v = 0, lwd = 5)
text(5, x1, labels = Fifth, cex = 1, adj = 0)
text(Golden_Age + 10, x1, 
     labels = paste(Golden_Age, "%", sep = ""), cex = 1)
x2 <- barplot(Neo_Liberal, horiz = TRUE, col = "cadetblue", 
              axes = FALSE, names.arg = Fifth, xlim = c(0, 80), 
              space = 0.5, las = 1, axisnames = TRUE)
title_2 <- "Neo Liberalism\n1980 ~ 2009"
title(main = title_2, cex.main = 2.0)
abline(v = 0, lwd = 5)
text(Neo_Liberal + c(rep(5, 4), 10), x2, 
     labels = paste(Neo_Liberal, "%", sep = ""), cex = 1)
# dev.copy(png, "../pics/income_increase_by_times.png", width = 960, height = 480)
```

<P style = "page-break-before:always">

## 한글화

```{r, data in kr, echo = FALSE}
library(extrafont)
Fifth_kr <- factor(5:1, levels = 5:1, labels = paste(5:1, "분위"))
# Golden_Age <- c(99, 115, 113, 101, 122)
# Neo_Liberal <- c(55, 25, 15, 7, -4)
Income_Gains_df_kr <- data.frame(Fifth_kr, Golden_Age, Neo_Liberal)
# str(Income_Gains_df_kr)
kable(Income_Gains_df_kr)
```

## Bar Plots

```{r, barplots in kr, echo = FALSE, fig.width = 12, fig.height = 6}
par(mfrow = c(1, 2), mai = c(1.0, 1.8, 0.8, 0.4) + 0.2, family = "Yj CHMSOOT Bold")
par(mfrow = c(1, 2), mai = c(1.0, 1.8, 0.8, 0.4) + 0.2)
x1_kr <- barplot(Golden_Age, horiz = TRUE, col = "tan", axes = FALSE, names.arg = "", xlim = c(0, 130), space = 0.5, las = 1, axisnames = TRUE)
title_1_kr <- "황금기\n1947 ~ 1979"
title(main = title_1_kr, cex.main = 2.0)
abline(v = 0, lwd = 5)
text(5, x1_kr, labels = Fifth_kr, cex = 1, adj = 0)
text(Golden_Age - 10, x1, labels = paste(Golden_Age, "%", sep =""), cex = 1)
x2_kr <- barplot(Neo_Liberal, horiz = TRUE, col = "cadetblue", axes = FALSE, names.arg = Fifth_kr, xlim = c(0, 80), space = 0.5, las = 1, axisnames = TRUE)
title_2_kr <- "신자유주의시기\n1980 ~ 2009"
title(main = title_2_kr, cex.main = 2.0)
abline(v = 0, lwd = 5)
text(Neo_Liberal + c(rep(5, 4), 10), x2_kr, labels = paste(Neo_Liberal, "%", sep = ""), cex = 1)
# dev.copy(png, "../pics/income_increase_by_times_kr.png", width = 960, height = 480)
```

## Save

```{r, save, echo = FALSE}
save.image("./G_age_N_liberal.RData")
```


