---
title: "US Top Income Share 1913 ~ 2015 (도표)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r, setup , include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Data

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 [`TabFig2015prel.xls`](http://eml.berkeley.edu//~saez/TabFig2015prel.xls) 를 손봐서 불러들인 것이다. 

```{r, data preparation, echo = FALSE, message = FALSE, results = 'hide'}
options(digits = 2)
load("US_top_income_shares_2015.RData")
ls()
```

<!--작업을 마친 자료파일은 `US_top_income_shares_15`이며, 이 자료의 구조와 앞의 몇 열의 값은 다음과 같다.-->

```{r, data structure, echo = FALSE, results = 'hide'}
library(knitr)
str(US_top_income_shares_15)
```

```{r, data for Table 3, echo = FALSE}
kable(US_top_income_shares_15[c(11:20, 41:51, 92:103), ])
```

### Top 10%의 소득점유율

소득 상위 10%(`P90_100`)의 소득점유율 변화

```{r, top 10, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_10_2015_72dpi_kr.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_10_2015_300dpi_kr.png", width = 1280, height = 720)
par(family = "")
x_lab <- "연도"
y_lab <- "소득 점유(%)"
plot(P90_100 ~ Year, data = US_top_income_shares_15, xlab = x_lab, ylab = y_lab, xlim = c(1910, 2020), ylim = c(30, 52), xaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2020, by = 10), labels = seq(1910, 2020, by = 10))
# lines(P95_99 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "red")
# lines(P90_95 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "blue")
abline(h = seq(30, 50, by = 5), lty = 3)
abline(v = seq(1910, 2020, by = 10), lty = 3)
# legend.text <- "Top 10% (incomes above $121,360 in 2015)")
# legend(x = 1940, y = 25, legend = legend.text, pch = 17, col = "black")
main_title <- "미국 상위 10% 소득 점유(1917 ~ 2015)"
title(main = main_title)
text(x = c(1927.5, 2007, 2012.5, 2016.5), y = c(50, 50, 51, 50.5), labels = c("1928", "2007", "2012", "2015"), pos = 3)
times_label <- c("대공황", "대번영", "대침체")
text(x = c(1935, 1965, 2015), y = c(48.5, 32, 46.5), label = times_label, cex = 1.5, col = "red")
# dev.copy(png, file = "../pics/US_top_income_share_1-4-5_2015_kr.png", width = 960, height = 540)
# dev.off()
```

### Top 10% 분할

소득 상위 10%(`P90_100`)를 상위 1%(`P99_100`), 차상위 4%(`P95_99`), 차차상위 5%(`P90_95`)로 분할

```{r, partition top 10, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_1-4-5_2015_72dpi_kr.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_1-4-5_2015_300dpi_kr.png", width = 1280, height = 720)
par(family = "")
plot(P99_100 ~ Year, data = US_top_income_shares_15, xlab = x_lab, ylab = y_lab, xlim = c(1910, 2020), ylim = c(5, 25), xaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2020, by = 10), labels = seq(1910, 2020, by = 10))
lines(P95_99 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "red")
lines(P90_95 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "blue")
abline(h = seq(5, 25, by = 5), lty = 3)
abline(v = seq(1910, 2020, by = 10), lty = 3)
legend_text_1 <- c("99-100%:$442,900 이상(2015년 기준)", "95-99%:$180,500-$442,900", "90-95%:$124,810-$180,500")
legend(x = 1947, y = 25, legend = legend_text_1, pch = 17, col = c("black", "red", "blue"))
main_title_1 <- "미국 상위 10% 소득 점유 분할 (1913 ~ 2015)"
title(main = main_title_1)
text(x = c(1924, 2007), y = c(23.5, 23.5), labels = c("1928", "2007"), pos = 3)
text(x = c(1935, 1965, 2015), y = c(22, 8, 18), label = times_label, cex = 1.5, col = "red")
# dev.copy(png, file = "../pics/US_top_income_share_1-4-5_2015_kr.png", width = 960, height = 540)
# dev.off()
```

<P style="page-break-before:always">

### Top 1% 분할

소득 상위 1%(`P99_100`)를 상위 0.1%(`P99.9_100`), 차상위 0.4%(`P99.5_99.9`), 차차상위 0.5%(`P99_99.5`)로 분할

```{r, partiotion top 1, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_0.1-0.4-0.5_2015_72dpi_kr.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_0.1-0.4-0.5_2015_300dpi_kr.png", width = 1280, height = 720)
par(family = "")
plot(P99.9_100 ~ Year, data = US_top_income_shares_15, xlab = x_lab, ylab = y_lab, xlim = c(1910, 2020), ylim = c(0, 13), xaxt = "n", yaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2020, by = 10), labels = seq(1910, 2020, by = 10))
axis(side = 2, at = seq(0, 12, by = 3), labels = seq(0, 12, by = 3))
lines(P99.5_99.9 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "red")
lines(P99_99.5 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "blue")
abline(h = seq(0, 12, by = 3), lty = 3)
abline(v = seq(1910, 2020, by = 10), lty = 3)
legend_text_2 <- c("99.9-100%:$2,045,000 이상(2015년 기준)", "99.5-99.9%:$682,080-$2,045,000", "99-99.5%:$442,900-$682,080")
legend(x = 1946, y = 13, legend = legend_text_2, pch = 17, col = c("black", "red", "blue"))
main_title_2 <- "미국 상위 1% 소득 점유 분할 (1913 ~ 2015)"
title(main = main_title_2)
text(x = c(1924, 2007), y = c(11, 12.5), labels = c("1928", "2007"), pos = 3)
text(x = c(1935, 1965, 2015), y = c(10, 2, 8), label = times_label, cex = 1.5, col = "red")
# dev.copy(png, file = "../pics/US_top_income_share_0.1-0.4-0.5_2015_kr.png", width = 960, height = 540)
# dev.off()
```

### Top 0.1% 분할

소득 상위 0.1%(`P99.9_100`)를 상위 0.01%(`P99.99_100`)와 다음 0.09%(`P99_9.99.99`)로 분할

```{r, partition top 1 0.01 vs 0.99, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_0.01-0.09_2015_72dpi_kr.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_0.01-0.09_2015_300dpi_kr.png", width = 1280, height = 720)
par(family = "")
plot(P99.99_100 ~ Year, data = US_top_income_shares_15, xlab = x_lab, ylab = y_lab, xlim = c(1910, 2020), ylim = c(0, 7), xaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2020, by = 10), labels = seq(1910, 2020, by = 10))
lines(P99.9_99.99 ~ Year, data = US_top_income_shares_15, type = "b", pch = 17, col = "blue")
abline(h = seq(0, 6, by = 2), lty = 3)
abline(v = seq(1910, 2020, by = 10), lty = 3)
legend_text_3 <- c("99.99-100%:$11,267,000 이상(2015년 기준)", "99.9-99.99%:$2,045,000-$11,267,000")
legend(x = 1945, y = 6.95, legend = legend_text_3, pch = 17, col = c("black", "blue"))
main_title_3 <- "미국 상위 0.1% 소득 점유 분할 (1913 ~ 2015)"
title(main = main_title_3)
text(x = c(1924, 2007), y = c(6.3, 6.3), labels = c("1928", "2007"), pos = 3)
text(x = c(1935, 1965, 2015), y = c(5.6, 0.5, 3.4), label = times_label, cex = 1.5, col = "red")
# dev.copy(png, file = "../pics/US_top_income_share_0.01-0.09_2015_kr.png", width = 960, height = 540)
# dev.off()
```

<P style="page-break-before:always">

## ggplot

### Data Reshaping

`reshape2` 패키지를 이용하여 wide format 을 long format 으로 변환하고 작업

```{r, reshape, echo = FALSE}
library(reshape2)
data_10_df <- US_top_income_shares_15[c("Year", "P90_100")]
data_10 <- US_top_income_shares_15[c("Year", "P99_100", "P95_99", "P90_95")]
data_10_melt <- melt(data_10, id.vars = "Year", measure.vars = c("P99_100", "P95_99", "P90_95"), variable.name = "Percentiles", value.name = "Share")
# str(data_10_melt)
data_1 <- US_top_income_shares_15[c("Year", "P99.9_100", "P99.5_99.9", "P99_99.5")]
data_1_melt <- melt(data_1, id.vars = "Year", measure.vars = c("P99.9_100", "P99.5_99.9", "P99_99.5"), variable.name = "Percentiles", value.name = "Share")
# str(data_1_melt)
data.01 <- US_top_income_shares_15[c("Year", "P99.99_100", "P99.9_99.99")]
data.01_melt <- melt(data.01, id.vars = "Year", measure.vars = c("P99.99_100", "P99.9_99.99"), variable.name = "Percentiles", value.name = "Share")
# str(data.01_melt)
```

### Top 10%의 소득점유(%)

```{r, Top 10 shares change, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
library(ggplot2)
source("theme_kr.R")
f0 <- ggplot(data_10_df, aes(x = Year, y = P90_100)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, fill = 1, size = 2, na.rm = TRUE) 
# f0
f1 <- f0 + 
  theme_bw()
# f1
f2 <- f1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# f2
f3 <- f2 + 
  scale_x_continuous(breaks = seq(1910, 2020, by = 10), limits = c(1910, 2020)) +
  scale_y_continuous(breaks = seq(30, 50, by = 5), limits = c(30, 52))
# f3
f4 <- f3 + 
#    theme.kr + 
   xlab(x_lab) + 
   ylab(y_lab)
# f4
f5 <- f4 + 
   ggtitle(main_title) + 
   theme(plot.title = element_text(size = 20))
# f5
f6 <- f5 + 
   annotate("text", x = c(1927.5, 2007, 2012.5), y = c(50.5, 50.5, 51.5), label = c(1928, 2007, 2012))
# f6
f7 <- f6 + 
  annotate("text", x = c(1935, 1965, 2015), y = c(48.5, 32, 46.5), label = times_label, colour = "red", family = "", size = 8)
```

```{r, Top 10 percent share ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
f7
# ggsave("../pics/US_top_income_share_10_2015_ggplot_kr.png", width = 12, height = 6.75)
```


### Top 10%의 분할 

```{r, Top 10 percent, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
# source("./theme_kr.R")
library(ggplot2)
g0 <- ggplot(data_10_melt, aes(x = Year, y = Share, colour = Percentiles)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, aes(fill = Percentiles), size = 2, na.rm = TRUE) 
# g0
g1 <- g0 + 
  theme_bw()
# g1
g2 <- g1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# g2
g3 <- g2 + 
  scale_x_continuous(breaks = seq(1910, 2020, by = 10), limits = c(1910, 2020)) +
  scale_y_continuous(breaks = seq(5, 25, by = 5), limits = c(5, 25))
# g3
g4 <- g3 + 
#   theme.kr + 
   xlab(x_lab) + 
   ylab(y_lab)
# g4
g5 <- g4 + 
   ggtitle(main_title_1) + 
   theme(plot.title = element_text(size = 20))
# g5
g6 <- g5 + 
   labs(colour = "Income Fractile", fill = "Income Fractile")
# g6
g7 <- g6 + 
   scale_colour_manual(name = "", values = c("black", "red", "blue"), labels = legend_text_1) +
   scale_fill_manual(name = "", values = c("black", "red", "blue"), labels = legend_text_1)
# g7
g8 <- g7 + 
   theme(legend.position =  c(0.5, 0.85))
# g8
g9 <- g8 + 
   guides(colour ="none")
# g9
g10 <- g9 + 
   theme(legend.title = element_blank(), legend.background = element_rect(fill = "white", colour = "black"))
# g10
g11 <- g10 + 
   theme(legend.key = element_blank())
# g11
g12 <- g11 + 
   annotate("text", x = c(1928, 2007), y = c(24.5, 24), label = c(1928, 2007))
# g12
g13 <- g12 + 
  annotate("text", x = c(1935, 1960, 2015), y = c(22, 8, 18), label = times_label, colour = "red", family = "", size = 8)
#  annotate("text", x = c(1935, 1965, 2015), y = c(22, 8, 18), label = times_label, colour = "red", size = 4)

```

```{r, Top 10 percent ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
g13
# ggsave("../pics/US_top_income_share_1-4-5_2015_ggplot_kr.png", width = 12, height = 6.75)
```

<P style="page-break-before:always">

### Top 1%의 분할 

```{r, Top 1 percent, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
h0 <- ggplot(data_1_melt, aes(x = Year, y = Share, colour = Percentiles)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, aes(fill = Percentiles), size = 2, na.rm = TRUE)
# h0
h1 <- h0 + 
  theme_bw()
# h1
h2 <- h1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# h2
h3 <- h2 + 
  scale_x_continuous(breaks = seq(1910, 2020, by = 10), limits = c(1910, 2020)) +
  scale_y_continuous(breaks = seq(0, 12, by = 3), limits = c(0, 13))
# h3
h4 <- h3 + 
#   theme.kr + 
   xlab(x_lab) + 
   ylab(y_lab)
# h4
h5 <- h4 + 
   ggtitle(main_title_2) + 
   theme(plot.title = element_text(size = 20))
# h5
h6 <- h5 + 
   labs(colour = "Income Fractile", fill = "Income Fractile")
# h6
h7 <- h6 + 
   scale_colour_manual(name = "", values = c("black", "red", "blue"), labels = legend_text_2) +
   scale_fill_manual(name = "", values = c("black", "red", "blue"), labels = legend_text_2)
# h7
h8 <- h7 + 
   theme(legend.position =  c(0.5, 0.85))
# h8
h9 <- h8 + 
   guides(colour ="none")
# h9
h10 <- h9 + 
   theme(legend.title = element_blank(), legend.background = element_rect(fill = "white", colour = "black"))
# h10
h11 <- h10 + 
   theme(legend.key = element_blank())
# h11
h12 <- h11 + 
   annotate("text", x = c(1925, 2007), y = c(11.5, 12.8), label = c(1928, 2007))
# h12
h13 <- h12 + 
  annotate("text", x = c(1935, 1960, 2015), y = c(9, 2, 8), label = times_label, colour = "red", family = "", size = 8)
#  annotate("text", x = c(1935, 1965, 2015), y = c(10, 2, 8), label = times_label, colour = "red", size = 4)
```

```{r, Top 1 percent ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
h13
# ggsave("../pics/US_top_income_share_0.1-0.4-0.5_2015_ggplot_kr.png", width = 12, height = 6.75)
```

### Top 0.1%의 분할 

```{r, Top 0.1 percent, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
j0 <- ggplot(data.01_melt, aes(x = Year, y = Share, colour = Percentiles)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, aes(fill = Percentiles), size = 2, na.rm = TRUE)
# j0
j1 <- j0 + 
  theme_bw()
# j1
j2 <- j1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# j2
j3 <- j2 + 
  scale_x_continuous(breaks = seq(1910, 2020, by = 10), limits = c(1910, 2020)) + 
  scale_y_continuous(breaks = seq(0, 6, by = 2), limits = c(0, 7))
# j3
j4 <- j3 + 
#   theme.kr + 
   xlab(x_lab) + 
   ylab(y_lab)
# j4
j5 <- j4 + 
   ggtitle(main_title_3) + 
   theme(plot.title = element_text(size = 20))
# j5
j6 <- j5 + 
   labs(colour = "Income Fractile", fill = "Income Fractile") 
# j6
j7 <- j6 + 
   scale_colour_manual(name = "", values = c("black", "blue"), labels = legend_text_3) +
   scale_fill_manual(name = "", values = c("black", "blue"), labels = legend_text_3)
# j7
j8 <- j7 + 
   theme(legend.position =  c(0.5, 0.85))
# j8
j9 <- j8 + 
   guides(colour ="none")
# j9
j10 <- j9 + 
   theme(legend.title = element_blank(), legend.background = element_rect(fill = "white", colour = "black"))
# j10
j11 <- j10 + 
   theme(legend.key = element_blank())
# j11
j12 <- j11 + 
   annotate("text", x = c(1928, 2007), y = c(6.8, 6.5), label = c(1928, 2007))
# j12
j13 <- j12 + 
  annotate("text", x = c(1935, 1960, 2015), y = c(5.6, 2.8, 3.0), label = times_label, colour = "red", family = "", size = 8)
#  annotate("text", x = c(1935, 1965, 2015), y = c(5.6, 0.5, 3.5), label = times_label, colour = "red", size = 4)
```

```{r, Top 0.1 percent ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
j13
# ggsave("../pics/US_top_income_share_0.01-0.09_2015_ggplot_kr.png", width = 12, height = 6.75)
```


