---
title: "US Top Income Share vs Tax Rates (1913 ~ 2017) - Data"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data Preparation

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 `TabFig2017prel.xls` 와 [Tax Foundation](http://taxfoundation.org/)에서 제공하는 자료를 손봐서 불러들인 것이다. 

```{r, data preparation, message = FALSE, echo = FALSE, results = 'markup'}
options(digits = 2)
library(xlsx)
library(knitr)
library(reshape2)
library(tidyverse)
library(magrittr)
load("US_top_income_shares_2017.RData")
# load("US_top_income_shares_vs_tax_rates_2017.rda")
# US_top_income_shares_17 <- read.xlsx("../data/TabFig2017prel.xlsx", sheetIndex = 9, sheetName = "Table A3", startRow = 6, endRow = 108, colIndex = c(1:7, 9:13), header = FALSE)
US_income_averages_17 <- read.xlsx("../data/TabFig2017prel.xlsx", 
                                   sheetIndex = 57, sheetName = "data-FigA1", 
                                   startRow = 4, endRow = 108, 
                                   colIndex = c(1:3, 5:6), header = FALSE)
# v_names <- read.xlsx("./data/TabFig2017prel.xlsx", sheetName = "Table A3", startRow = 4, endRow = 4, colIndex = c(2:7, 9:14), colClasses = character, header = FALSE)
# str(US_top_income_shares_17)
v_names <- c("Year", "Bottom_99", "Top_1", "Bottom_99_K", "Top_1_K")
names(US_income_averages_17) <- v_names
tax_rates <- read.table("../data/federal_income_tax_rates.txt", 
                        skip = 1, header = FALSE)
names(tax_rates) <- c("Year", "Lowest", "Marginal")
top_income_tax <- cbind(US_top_income_shares_17[c("Year", "P99_100")], US_income_averages_17[c("Bottom_99", "Top_1", "Bottom_99_K", "Top_1_K")], tax_rates[2:3])
Rate_99 <- US_income_averages_17[, "Bottom_99"] / US_income_averages_17[, "Bottom_99"][1] * 100
Rate_1 <- US_income_averages_17[, "Top_1"] / US_income_averages_17[, "Top_1"][1] * 100
Rate_99_K <- US_income_averages_17[, "Bottom_99_K"] / US_income_averages_17[, "Bottom_99_K"][1] * 100
Rate_1_K <- US_income_averages_17[, "Top_1_K"] / US_income_averages_17[, "Top_1_K"][1] * 100
```

선형변환에 사용할 함수 작성  `q = x`로 하면 변수의 관찰값 전체를 변환. `q`는 그 중 일부의 변환된 값을 보고자 할 때 입력

```{r}
z <- function(x, q, a = min(x), b = max(x)) {
  (q - a) / (b - a)
}
#> 0애서 1사이의 범위로 변환
top_income_tax$P99_100_z <- top_income_tax$P99_100 %>%
  z(., .)
top_income_tax$Marginal_z <- top_income_tax$Marginal %>%
  z(., .)
Rate_99_z <- Rate_99 %>%
  z(., ., a = min(c(Rate_99, Rate_1)), b = max(c(Rate_99, Rate_1)))
Rate_1_z <- Rate_1 %>%
  z(., ., a = min(c(Rate_99, Rate_1)), b = max(c(Rate_99, Rate_1)))
Rate_99_K_z <- Rate_99_K %>%
  z(., ., a = min(c(Rate_99_K, Rate_1_K)), b = max(c(Rate_99_K, Rate_1_K)))
Rate_1_K_z <- Rate_1_K %>%
  z(., ., a = min(c(Rate_99_K, Rate_1_K)), b = max(c(Rate_99_K, Rate_1_K)))
kable(cbind(top_income_tax, Rate_99 = Rate_99_z, Rate_1 = Rate_1_z, Rate_99_K = Rate_99_K_z, Rate_1_K = Rate_1_K_z))
M_tbl <- top_income_tax %>%
  select(c("Year", "P99_100_z", "Marginal_z")) %>%
  as_tibble %>%
  gather(key = "Variables", value = "Values", -Year) 
str(M_tbl)
M_melt <- melt(data.frame(top_income_tax[c("Year", "P99_100_z", "Marginal_z")]),
       id.vars = "Year", 
       measure.vars = c("P99_100_z", "Marginal_z"),
       variable.name = c("Variables"),
       value.name = "Values")
str(M_melt)
Rates_tbl <- top_income_tax %>%
  select(c("Year", "Marginal_z")) %>%
  data.frame(Rate_99_z, Rate_1_z) %>%
  as_tibble %>%
  gather(key = "Variables", value = "Values", -Year)
str(Rates_tbl)
Rates_melt <- melt(data.frame(top_income_tax[c("Year", "Marginal_z")], Rate_99_z, Rate_1_z),
       id.vars = "Year", 
       measure.vars = c("Marginal_z", "Rate_99_z", "Rate_1_z"),
       variable.name = c("Variables"),
       value.name = "Values")
str(Rates_melt)
Rates_K_tbl <- top_income_tax %>%
  select(c("Year", "Marginal_z")) %>%
  data.frame(Rate_99_K_z, Rate_1_K_z) %>%
  as_tibble %>%
  gather(key = "Variables", value = "Values", -Year)
str(Rates_K_tbl)
Rates_K_melt <- melt(data.frame(top_income_tax[c("Year", "Marginal_z")], Rate_99_K_z, Rate_1_K_z),
       id.vars = "Year", 
       measure.vars = c("Marginal_z", "Rate_99_K_z", "Rate_1_K_z"),
       variable.name = c("Variables"),
       value.name = "Values")
str(Rates_K_melt)
```

## Save

```{r, save.image}
save.image(file = "US_top_income_shares_vs_tax_rates_2017.RData")
```

