---
title: "US Top Income Shares 1913-2017 (Data)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data Preparation

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 [`TabFig2017prel.xls`](http://eml.berkeley.edu//~saez/TabFig2017prel.xls)` 를 손봐서 불러들인 것이다. 

```{r, data preparation, message = FALSE, echo = FALSE, results = 'hide'}
options(digits = 3)
library(xlsx)
US_top_income_shares_17 <- read.xlsx("../data/TabFig2017prel.xlsx",
                                     sheetIndex = 9, 
                                     sheetName = "Table A3", 
                                     startRow = 6, 
                                     endRow = 110, 
                                     colIndex = c(1:7, 9:13), 
                                     colClasses = c("integer", rep("numeric", 12)),
                                     header = FALSE)
v_names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
names(US_top_income_shares_17) <- v_names
str(US_top_income_shares_17)
ls()
```

<!--작업을 마친 자료파일은 `US_top_income_shares_17`이며, 이 자료의 구조와 앞의 몇 열의 값은 다음과 같다.-->

```{r, data structure, echo = FALSE}
library(knitr)
kable(format(US_top_income_shares_17, digits = 1, nsmall = 1), align = "r")
```

## Save Data

```{r, save.image}
saveRDS(US_top_income_shares_17, file = "./US_top_income.RDS")
save.image(file = "US_top_income_shares_2017.RData")
```
